### PR TITLE
Fixed image in collection and item preview

### PR DESCRIPTION
**Pull request by Nico-Connor-Personal**
# Description

Fixed placeholder not showing up

### CODE REVIEW

**Comment by Nico-Connor-Personal** [comment]
image

image

**Comment by vanessa-cooper** [comment]
Thanks Nico-Connor, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job Nico-Connor! You're now able to merge the PR.

**Pull request merged**
